import swaggerJsdoc from 'swagger-jsdoc';

export const getApiDocs = () => {
  const spec = swaggerJsdoc({
    definition: {
      openapi: '3.0.0',
      info: {
        title: 'HTB Global API Documentation',
        version: '1.0.0',
        description: 'API documentation for HTB Global institutional lending platform. This documents the available endpoints and the core database schema for applications and profiles. Submitted application data is stored in Supabase today and is structured for forwarding to the MSD backend integration.',
      },
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
          },
        },
        schemas: {
          Application: {
            type: 'object',
            properties: {
              id: { type: 'string', format: 'uuid' },
              reference: { type: 'string', example: 'LN-1234' },
              status: { type: 'string', enum: ['draft', 'submitted', 'approved', 'rejected'] },
              first_name: { type: 'string' },
              last_name: { type: 'string' },
              national_id: { type: 'string' },
              store_id: { type: 'integer', nullable: true },
              store_name: { type: 'string', nullable: true },
              product_name: { type: 'string' },
              retail_price: { type: 'number' },
              deposit_amount: { type: 'number' },
              balance_amount: { type: 'number' },
              tenure_months: { type: 'integer', nullable: true },
              physical_address: { type: 'string' },
              mobile_number: { type: 'string' },
              email_address: { type: 'string', format: 'email' },
              employer_name: { type: 'string', nullable: true },
              is_civil_servant: { type: 'boolean' },
              employer_no: { type: 'string', nullable: true, description: 'EC number for civil servants.' },
              ministry: { type: 'string', nullable: true },
              employer_phone: { type: 'string', description: 'Employer main phone number.' },
              employer_contact_person: { type: 'string', description: 'HR manager, supervisor, or other employer contact for verification.' },
              employer_email: { type: 'string', format: 'email', nullable: true },
              employer_address: { type: 'string', description: 'Employer physical address.' },
              kin_full_name: { type: 'string' },
              kin_relationship: { type: 'string' },
              kin_mobile: { type: 'string' },
              kin_address: { type: 'string' },
              id_copy_url: { type: 'string', format: 'uri' },
              payslip_url: { type: 'string', format: 'uri' },
              photo_url: { type: 'string', format: 'uri' },
              created_at: { type: 'string', format: 'date-time' },
            },
            description: 'Loan application record. This shape is also the canonical payload basis for future MSD backend submission.',
          },
          Profile: {
            type: 'object',
            properties: {
              id: { type: 'string', format: 'uuid' },
              full_name: { type: 'string' },
              avatar_url: { type: 'string', format: 'uri' },
              first_name: { type: 'string', nullable: true },
              last_name: { type: 'string', nullable: true },
              national_id: { type: 'string', nullable: true },
              date_of_birth: { type: 'string', nullable: true },
              gender: { type: 'string', nullable: true },
              physical_address: { type: 'string', nullable: true },
              mobile_number: { type: 'string', nullable: true },
              email_address: { type: 'string', format: 'email', nullable: true },
              nok_full_name: { type: 'string', nullable: true },
              nok_address: { type: 'string', nullable: true },
              nok_mobile_number: { type: 'string', nullable: true },
              nok_relationship: { type: 'string', nullable: true },
              employer_name: { type: 'string', nullable: true },
              employer_no: { type: 'string', nullable: true },
              ministry: { type: 'string', nullable: true },
              is_civil_servant: { type: 'boolean' },
              monthly_income: { type: 'string', nullable: true },
              employment_phone: { type: 'string', nullable: true },
              employer_contact_person: { type: 'string', nullable: true },
              employer_email: { type: 'string', format: 'email', nullable: true },
              employer_address: { type: 'string', nullable: true },
              is_profile_complete: { type: 'boolean' },
              updated_at: { type: 'string', format: 'date-time' },
            },
          },
          MsdSubmissionPayload: {
            allOf: [{ $ref: '#/components/schemas/Application' }],
            description: 'Future outbound payload to the MSD backend. Keep this aligned with Application until the external MSD contract is finalized.',
          },
        },
      },
      security: [],
    },
    apis: ['./src/app/api/**/*.ts'], // Search for jsdoc comments in api routes
  });
  return spec;
};
