/**
 * MS365 INTEGRATION API ROUTE
 * ─────────────────────────────────────────────────────────────────────────────
 * POST /api/ms365
 *
 * Called by: src/app/(application)/apply/summary/page.tsx → handleSubmit()
 * Fired:     Non-blocking (fire-and-forget). A failure here NEVER stops the user.
 *
 * What this route does on each loan application submission:
 *   1. Creates a new item in the SharePoint "Loan Applications" list
 *   2. Uploads the generated PDF to the SharePoint Document Library
 *   3. Updates the list item with the PDF's URL
 *   4. Sends an Outlook notification email to the business inbox
 *
 * Steps 1 & 2 run in parallel (Promise.all) for speed.
 *
 * SETUP REQUIRED:
 *   - Azure App Registration with permissions: Sites.ReadWrite.All, Files.ReadWrite.All, Mail.Send
 *   - SharePoint List named "Loan Applications" with 29 columns (see MS365-INTEGRATION.md)
 *   - SharePoint Document Library folder named "Loan Applications"
 *   - All MS365_* environment variables filled in (.env / Vercel settings)
 *
 * Full setup guide: /MS365-INTEGRATION.md (project root)
 *
 * ENV VARS REQUIRED (see .env for placeholders):
 *   MS365_TENANT_ID, MS365_CLIENT_ID, MS365_CLIENT_SECRET
 *   MS365_SHAREPOINT_SITE_ID, MS365_SHAREPOINT_LIST_ID, MS365_SHAREPOINT_DRIVE_ID
 *   MS365_SENDER_UPN, MS365_NOTIFY_EMAIL
 *
 * RELATED FILES:
 *   - Caller:      src/app/(application)/apply/summary/page.tsx
 *   - Data source: src/lib/store.ts  (Zustand store — all form fields live here)
 *   - PDF gen:     src/utils/pdf-generator.ts
 *   - Supabase:    src/utils/supabase/client.ts + server.ts
 *   - Email route: src/app/api/send-confirmation/route.ts
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { NextResponse } from 'next/server';
import { ClientSecretCredential } from '@azure/identity';
import { Client } from '@microsoft/microsoft-graph-client';
import { TokenCredentialAuthenticationProvider } from '@microsoft/microsoft-graph-client/authProviders/azureTokenCredentials';

/**
 * Shape of the payload sent from summary/page.tsx.
 * All fields come directly from the Zustand store: src/lib/store.ts
 * The pdfBase64 field is a data URI generated by: src/utils/pdf-generator.ts
 */
interface MS365Payload {
  reference: string;              // e.g. "LN-4821" — generated in summary/page.tsx
  selectedStoreId: number | null; // src/lib/store.ts → selectedStoreId
  selectedStoreName: string;      // src/lib/store.ts → selectedStoreName
  lookup: {
    nationalId: string;           // src/lib/store.ts → lookup.nationalId
  };
  basicInfo: {
    firstName: string;            // src/lib/store.ts → basicInfo.firstName
    lastName: string;
    dateOfBirth: string;
    gender: string;
    photoUrl?: string;            // base64 selfie — stored in Supabase, not sent to SharePoint
  };
  contactDetails: {
    physicalAddress: string;      // src/lib/store.ts → contactDetails.*
    mobileNumber: string;
    emailAddress: string;
  };
  employmentDetails: {
    employerName: string;         // src/lib/store.ts → employmentDetails.*
    isCivilServant: boolean | null;
    employerNo: string;           // EC number — only for civil servants
    ministry: string;             // only for civil servants
    phoneNumber: string;
    contactPerson: string;
    emailAddress: string;
    physicalAddress: string;
  };
  purchaseDetails: {
    productName: string;          // src/lib/store.ts → purchaseDetails.*
    retailPrice: string;          // stored as string in Zustand, parsed to float here
    depositAmount: string;
    tenureMonths: string;
  };
  nextOfKin: {
    fullName: string;             // src/lib/store.ts → nextOfKin.*
    relationship: string;
    mobileNumber: string;
    address: string;
  };
  documentUploads: {
    idCopyUrl: string;            // Supabase Storage public URL — uploaded in document-uploads/page.tsx
    payslipUrl: string;           // Supabase Storage public URL
  };
  pdfBase64: string;              // data:application/pdf;base64,... from pdf-generator.ts
}

/**
 * Builds an authenticated Microsoft Graph client using Client Credentials flow.
 * Uses: MS365_TENANT_ID, MS365_CLIENT_ID, MS365_CLIENT_SECRET from .env
 * Azure permissions needed: Sites.ReadWrite.All, Files.ReadWrite.All, Mail.Send
 */
function getGraphClient(): Client {
  const credential = new ClientSecretCredential(
    process.env.MS365_TENANT_ID!,
    process.env.MS365_CLIENT_ID!,
    process.env.MS365_CLIENT_SECRET!
  );
  const authProvider = new TokenCredentialAuthenticationProvider(credential, {
    scopes: ['https://graph.microsoft.com/.default'],
  });
  return Client.initWithMiddleware({ authProvider });
}

/**
 * Creates a new list item in the SharePoint "Loan Applications" list.
 *
 * SharePoint list must be set up with 29 columns — see MS365-INTEGRATION.md Step 4.
 * Uses: MS365_SHAREPOINT_SITE_ID, MS365_SHAREPOINT_LIST_ID from .env
 *
 * The field keys (Title, Status, StoreName, etc.) must exactly match the
 * Internal Names of the columns in your SharePoint list.
 *
 * Returns the new SharePoint list item ID (used to attach the PDF URL after upload).
 */
async function createSharePointListItem(
  client: Client,
  data: MS365Payload,
  balance: number
): Promise<string> {
  const siteId = process.env.MS365_SHAREPOINT_SITE_ID!;
  const listId = process.env.MS365_SHAREPOINT_LIST_ID!;

  const response = await client
    .api(`/sites/${siteId}/lists/${listId}/items`)
    .post({
      fields: {
        // ── Identity & Store ──────────────────────────────────────────────────
        Title:           data.reference,          // LN-XXXX — used as the list item title
        Status:          'Submitted',
        StoreName:       data.selectedStoreName,
        StoreId:         data.selectedStoreId,
        NationalId:      data.lookup.nationalId,
        // ── Personal Info (collected in: apply/basic-info/page.tsx) ──────────
        FirstName:       data.basicInfo.firstName,
        LastName:        data.basicInfo.lastName,
        DateOfBirth:     data.basicInfo.dateOfBirth || null,
        Gender:          data.basicInfo.gender,
        // ── Contact Details (collected in: apply/contact-details/page.tsx) ───
        MobileNumber:    data.contactDetails.mobileNumber,
        EmailAddress:    data.contactDetails.emailAddress,
        PhysicalAddress: data.contactDetails.physicalAddress,
        // ── Employment (collected in: apply/employment-details/page.tsx) ─────
        EmployerName:          data.employmentDetails.employerName,
        IsCivilServant:        data.employmentDetails.isCivilServant ?? false,
        EmployerNo:            data.employmentDetails.employerNo || '',   // civil servants only
        Ministry:              data.employmentDetails.ministry || '',     // civil servants only
        EmployerPhone:         data.employmentDetails.phoneNumber,
        EmployerContactPerson: data.employmentDetails.contactPerson || '',
        EmployerEmail:         data.employmentDetails.emailAddress || '',
        EmployerAddress:       data.employmentDetails.physicalAddress || '',
        // ── Purchase / Loan (collected in: apply/purchase-details/page.tsx) ──
        ProductName:     data.purchaseDetails.productName,
        RetailPrice:     parseFloat(data.purchaseDetails.retailPrice) || 0,
        DepositAmount:   parseFloat(data.purchaseDetails.depositAmount) || 0,
        BalanceAmount:   balance,                  // computed: retailPrice - depositAmount
        TenureMonths:    parseInt(data.purchaseDetails.tenureMonths) || 0,
        // ── Next of Kin (collected in: apply/next-of-kin/page.tsx) ───────────
        KinFullName:     data.nextOfKin.fullName,
        KinRelationship: data.nextOfKin.relationship,
        KinMobile:       data.nextOfKin.mobileNumber,
        KinAddress:      data.nextOfKin.address,
        // ── Documents (uploaded in: apply/document-uploads/page.tsx) ─────────
        // These are Supabase Storage public URLs, not the files themselves
        IdCopyUrl:       data.documentUploads.idCopyUrl || '',
        PayslipUrl:      data.documentUploads.payslipUrl || '',
        // PdfDocumentUrl is set separately after uploadPdfToDrive() completes
        // ── System ───────────────────────────────────────────────────────────
        SubmissionDate:  new Date().toISOString(),
      },
    });

  return response.id as string;
}

/**
 * Uploads the generated PDF to the SharePoint Document Library.
 *
 * Target folder: "Loan Applications" (must exist — create it manually in SharePoint)
 * File name:     LN-XXXX.pdf (matches the application reference)
 * Uses: MS365_SHAREPOINT_SITE_ID, MS365_SHAREPOINT_DRIVE_ID from .env
 *
 * The PDF is generated by: src/utils/pdf-generator.ts → generateLoanPDF()
 * It arrives here as a base64 data URI (data:application/pdf;base64,...)
 * We strip the prefix and convert to a Buffer for the Graph API PUT request.
 *
 * Returns the SharePoint web URL of the uploaded file (stored back in the list item).
 */
async function uploadPdfToDrive(
  client: Client,
  pdfBase64DataUri: string,
  reference: string
): Promise<string> {
  const siteId  = process.env.MS365_SHAREPOINT_SITE_ID!;
  const driveId = process.env.MS365_SHAREPOINT_DRIVE_ID!;

  // Strip the "data:application/pdf;base64," prefix to get raw base64
  const base64Data = pdfBase64DataUri.split(',')[1];
  const pdfBuffer  = Buffer.from(base64Data, 'base64');
  const fileName   = `${reference}.pdf`;  // e.g. LN-4821.pdf

  // Graph simple upload — works for files under 4 MB (all application PDFs will be well under 1 MB)
  const uploadResponse = await client
    .api(`/sites/${siteId}/drives/${driveId}/root:/Loan Applications/${fileName}:/content`)
    .header('Content-Type', 'application/pdf')
    .put(pdfBuffer);

  return uploadResponse.webUrl as string;
}

/**
 * Patches the SharePoint list item with the PDF's URL after upload completes.
 * This links the record in the list to the file in the Document Library.
 *
 * Called after both createSharePointListItem() and uploadPdfToDrive() succeed.
 * Uses: MS365_SHAREPOINT_SITE_ID, MS365_SHAREPOINT_LIST_ID from .env
 */
async function updateListItemWithPdfUrl(
  client: Client,
  itemId: string,   // returned by createSharePointListItem()
  pdfUrl: string    // returned by uploadPdfToDrive()
): Promise<void> {
  const siteId = process.env.MS365_SHAREPOINT_SITE_ID!;
  const listId = process.env.MS365_SHAREPOINT_LIST_ID!;

  await client
    .api(`/sites/${siteId}/lists/${listId}/items/${itemId}/fields`)
    .patch({ PdfDocumentUrl: pdfUrl });
}

/**
 * Sends an Outlook email to the business inbox with a summary table and PDF attached.
 *
 * Sender: MS365_SENDER_UPN (must be a licensed mailbox in your tenant)
 * To:     MS365_NOTIFY_EMAIL (the business inbox that receives new application alerts)
 *
 * Only called if both MS365_NOTIFY_EMAIL and MS365_SENDER_UPN are set in .env.
 * Skipped silently if either is missing.
 */
async function sendOutlookNotification(
  client: Client,
  data: MS365Payload,
  balance: number
): Promise<void> {
  const senderUpn   = process.env.MS365_SENDER_UPN!;
  const notifyEmail = process.env.MS365_NOTIFY_EMAIL!;

  // Strip data URI prefix — contentBytes must be raw base64, not a data URI
  const base64Data = data.pdfBase64.split(',')[1];

  await client.api(`/users/${senderUpn}/sendMail`).post({
    message: {
      subject: `New Loan Application: ${data.reference} — ${data.basicInfo.firstName} ${data.basicInfo.lastName}`,
      body: {
        contentType: 'HTML',
        content: `
          <h2>New Loan Application Received</h2>
          <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-family:sans-serif;font-size:14px">
            <tr><td><b>Reference</b></td><td>${data.reference}</td></tr>
            <tr><td><b>Customer</b></td><td>${data.basicInfo.firstName} ${data.basicInfo.lastName}</td></tr>
            <tr><td><b>National ID</b></td><td>${data.lookup.nationalId}</td></tr>
            <tr><td><b>Mobile</b></td><td>${data.contactDetails.mobileNumber}</td></tr>
            <tr><td><b>Email</b></td><td>${data.contactDetails.emailAddress}</td></tr>
            <tr><td><b>Store</b></td><td>${data.selectedStoreName}</td></tr>
            <tr><td><b>Product</b></td><td>${data.purchaseDetails.productName}</td></tr>
            <tr><td><b>Retail Price</b></td><td>$${parseFloat(data.purchaseDetails.retailPrice).toFixed(2)}</td></tr>
            <tr><td><b>Deposit</b></td><td>$${parseFloat(data.purchaseDetails.depositAmount).toFixed(2)}</td></tr>
            <tr><td><b>Balance (Loan Amount)</b></td><td>$${balance.toFixed(2)}</td></tr>
            <tr><td><b>Employer</b></td><td>${data.employmentDetails.employerName}</td></tr>
            <tr><td><b>Civil Servant?</b></td><td>${data.employmentDetails.isCivilServant ? 'Yes' : 'No'}</td></tr>
          </table>
          <p style="margin-top:16px;color:#666">PDF application is attached.</p>
        `,
      },
      toRecipients: [{ emailAddress: { address: notifyEmail } }],
      attachments: [
        {
          '@odata.type': '#microsoft.graph.fileAttachment',
          name:          `Application-${data.reference}.pdf`,
          contentType:   'application/pdf',
          contentBytes:  base64Data,
        },
      ],
    },
    saveToSentItems: false,
  });
}

/**
 * POST handler — entry point for /api/ms365
 *
 * Called from: src/app/(application)/apply/summary/page.tsx → handleSubmit()
 * This is intentionally fire-and-forget from the caller. The response is logged
 * but never awaited, so the user always reaches /success regardless of outcome.
 *
 * Returns HTTP 200 even on internal errors (see catch block) — this prevents
 * network-level retries and keeps the caller's .catch() from triggering.
 *
 * If any required env var is missing, returns { skipped: true } and exits early.
 * This is the expected state before Azure is configured.
 */
export async function POST(req: Request) {
  try {
    const payload = (await req.json()) as MS365Payload;

    // Guard: skip entirely if Azure credentials are not configured yet
    // → Fill these in .env and Vercel settings (see MS365-INTEGRATION.md Step 7)
    const requiredEnvVars = [
      'MS365_TENANT_ID',
      'MS365_CLIENT_ID',
      'MS365_CLIENT_SECRET',
      'MS365_SHAREPOINT_SITE_ID',
      'MS365_SHAREPOINT_LIST_ID',
      'MS365_SHAREPOINT_DRIVE_ID',
    ];
    const missing = requiredEnvVars.filter((v) => !process.env[v]);
    if (missing.length > 0) {
      console.warn(`MS365: Missing env vars: ${missing.join(', ')}. Skipping.`);
      return NextResponse.json({ success: false, skipped: true, reason: 'missing_config' });
    }

    const client  = getGraphClient();
    const balance = Math.max(
      0,
      (parseFloat(payload.purchaseDetails.retailPrice) || 0) -
        (parseFloat(payload.purchaseDetails.depositAmount) || 0)
    );

    // Run list item creation and PDF upload simultaneously — they don't depend on each other
    const [listItemId, pdfUrl] = await Promise.all([
      createSharePointListItem(client, payload, balance),  // → SharePoint list
      uploadPdfToDrive(client, payload.pdfBase64, payload.reference), // → Document Library
    ]);

    // Now that we have both the list item ID and the PDF URL, link them together
    await updateListItemWithPdfUrl(client, listItemId, pdfUrl);

    // Send Outlook notification — only if both sender and recipient are configured
    if (process.env.MS365_NOTIFY_EMAIL && process.env.MS365_SENDER_UPN) {
      await sendOutlookNotification(client, payload, balance);
    }

    return NextResponse.json({ success: true, listItemId, pdfUrl });
  } catch (error: any) {
    console.error('MS365 Integration Error:', error?.message ?? error);
    // Intentional HTTP 200 — the caller (summary/page.tsx) uses fire-and-forget.
    // Returning 200 prevents the fetch from throwing, keeping the .catch() clean.
    return NextResponse.json({ success: false, error: error?.message ?? 'Unknown error' });
  }
}
